### ISSUE TITLE
Concurrent vault access under different identities

### ISSUE THREAD

**Issue by davehope** [jborean93/SecretManagement.DpapiNG#8]
Concurrent access, from processes running under different user identities, results in a failure to retrieve the secret and an exception being thrown:

```
Get-Secret : The process cannot access the file 'C:\Scripts\Data\dpaping.vault' because it is being used by another process.
At line:3 char:10
+     $r = Get-Secret -Name 'demo' -Vault DPAPING
+          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-Secret], IOException
    + FullyQualifiedErrorId : System.IO.IOException,Microsoft.PowerShell.SecretManagement.GetSecretCommand
 ```

This can be reproduced by running the following code under two accounts at the same time, ensuring the vault "DPAPING" points to the same file and that the protection descriptor allows access.

```
while($true)
{
    $c = Get-Secret -Name 'demo' -Vault DPAPING
}
```

**Comment by davehope** [comment]
Exploring this issue a little further, it looks like LiteDB is used with the relevant section of code in DpapiNGSecretBase.ProcessRecord(), src/SecretManagement.DpapiNG.Module/DpapiNGSecretBase.cs

On that basis, the issue can be reproduced in an approach similar to my previous post but with:

```
Add-Type -Path 'C:\Program Files\WindowsPowerShell\Modules\SecretManagement.DpapiNG\0.3.0\SecretManagement.DpapiNG.Extension\bin\net472\LiteDB.dll'
$dbPath = 'C:\Scripts\Data\dpaping.vault'
while($true)
{
    [LiteDB.LiteDatabase]$db = [LiteDB.LiteDatabase]::new($dbPath)
    $secrets = $db.GetCollection('secrets')
    $db.Dispose()
}
```

If shared connection mode is used, the two processes happily execute at the same time.

```    [LiteDB.LiteDatabase]$db = [LiteDB.LiteDatabase]::new("Filename=$dbPath;connection=shared")```

Unfortunately the validation in ProcessRecord() would prevent me just setting the path as a connection string in VaultParameters.

Perhaps one option could be to check for a connection property on VaultParameters, allowing people to set shared mode if needed?

**Comment by jborean93** [comment]
Thanks for the bug report, it looks like it should be safe to use shared mode at least with `Get-*` operations but I'll have to do some more research to see how it actually works when multiple connections try to write to the same database. I don't think the performance overhead of opening it always in shared mode should be too great so reducing the options needed is always nice.

**Comment by jborean93** [comment]
I've opened https://github.com/jborean93/SecretManagement.DpapiNG/issues/8 which uses the shared connection as well as marking read only operations where possible to hopefully help with concurrency problems. As I can't reliably test such scenarios in CI I'll need to do some manual tests locally to verify this actually helps but I think it will.

**Comment by davehope** [comment]
Thanks! I've tested concurrency of Get-Secret:

- Running powershell_ise under two separate identities with module 0.3.0 the issue occurs
- Popped the artifact from #10 somewhere, updated PSModulePath, unloaded the old module and loaded the new, am not able to reproduce the issue

I've also tested:
- In one ISE instance running under one identity, run the get-secret call in a loop
- In a second ISE instance, under a separate identity, create new secrets in a loop. No issues

```
$i=0
while($true)
{
    $c = Get-Secret -Name 'Demo3' -Vault DPAPING

    $name = "test" + ++$i
    $c = 'test' | ConvertTo-SecureString -AsPlainText -Force
    "converted"
    $desc = New-DpapiNGDescriptor | Add-DpapiNGDescriptor -Or -Sid ([System.Security.Principal.NTAccount]'xxx') | Add-DpapiNGDescriptor -Or -Sid ([System.Security.Principal.NTAccount]'yyy')
    "descriptor"
    Set-Secret -Name $name -Secret $c -Vault DPAPING @desc
    "set"
}
```

**Comment by jborean93** [comment]
Awesome, thanks for testing this and confirming it works.

On a side note, it looks like the `-Sid` parameter could probably be improved by accepting just a string that represents an `NTAccount` rather than forcing you to build the type. I know it supports an explicit SID but having it translate a non-SID string would be nice so I'll look at adding support for that as well.
